/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplesRouteImport } from './routes/temples'
import { Route as IndexRouteImport } from './routes/index'

const TemplesRoute = TemplesRouteImport.update({
  id: '/temples',
  path: '/temples',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/temples': typeof TemplesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/temples': typeof TemplesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/temples': typeof TemplesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/temples'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/temples'
  id: '__root__' | '/' | '/temples'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplesRoute: typeof TemplesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temples': {
      id: '/temples'
      path: '/temples'
      fullPath: '/temples'
      preLoaderRoute: typeof TemplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplesRoute: TemplesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
